---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Include setup tasks
- include_tasks: "{{ ansible_os_family }}-setup.yml"
  tags: ['include_tasks']
