---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Include setup tasks
- include_tasks: "{{ ansible_os_family }}-setup.yml"
  tags: ['include_tasks']

- name: Setup plugins on ansible >=2.10
  rabbitmq_plugin:
    names: "{{ item }}"
    state: enabled
    broker_state: offline
  with_items: "{{ rabbitmq_plugins }}"
  tags: ['rabbitmq']
  notify: rabbitmq-restarted-handler
  when: ansible_version.full is version('2.10', '>=')

- name: Setup plugins on ansible <2.10
  rabbitmq_plugin:
    names: "{{ item }}"
    state: enabled
  with_items: "{{ rabbitmq_plugins }}"
  tags: ['rabbitmq']
  notify: rabbitmq-restarted-handler
  when: ansible_version.full is version('2.10', '<')

- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- name: Install default admin user
  rabbitmq_user:
    user: admin
    password: "{{ rabbimq_admin_password }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

- include_tasks: "cluster.yml"
  when: rabbitmq_ec2_cluster
