---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: rabbitmq-restarted-handler
  service:
    name: "{{ rabbitmq_service_name }}"
    state: restarted
    enabled: true
  tags: rabbitmq
